/*
 * toString.gr
 * Copyright (c) 2025 Jake Follest
 *
 * This file uses code from `libs/doc.gr`, which is licensed under the GPL.
 * Your use of this file is therefore subject to the GPL license.
 *
 * Original contributions by Jake Follest are MIT licensed, but redistribution
 * must comply with the GPL where the GPL code is used.
 */

/**
 * Module for converting Grain values to their string representations.
 *
 * @example toString(true) == "true"
 * @example toString(123) == "123"
 */
@runtimeMode
module ToString

from "runtime/unsafe/wasmref" include WasmRef
use WasmRef.{ module WasmArrayRef }
from "runtime/unsafe/wasmi32" include WasmI32
from "runtime/unsafe/wasmf64" include WasmF64
from "runtime/unsafe/conv" include Conv
from "runtime/unsafe/tags" include Tags
from "runtime/bigint" include Bigint
from "runtime/numberUtils" include NumberUtils
from "runtime/dataStructures" include DataStructures
use DataStructures.{
  allocateString,
  // Tagging
  tagSimpleNumber,
  untagSimpleNumber,
  // Short Values
  untagChar,
  untagInt8,
  untagInt16,
  untagUint8,
  untagUint16,
}
from "runtime/utf8" include Utf8
use Utf8.{ usvEncodeLength, writeUtf8CodePoint }
from "./libs/grainValue.gr" include GrainValue
from "./libs/doc.gr" include Doc

primitive (!) = "@not"
primitive (&&) = "@and"
primitive (||) = "@or"
primitive (is) = "@is"
primitive magic = "@magic"
primitive box = "@box"
primitive unbox = "@unbox"

@unsafe
let _VISITED_BIT = 0x1n

// Computes the escaped length of a usv
@unsafe
let computeEscapedUSVLength = (usv: WasmI32, isString: Bool) => {
  match (usv) {
    0x08n | 0x0Cn | 0x0An | 0x0Dn | 0x09n | 0x0Bn | 0x5Cn => 2n,
    0x27n when !isString => 2n,
    0x22n when isString => 2n,
    _ => usvEncodeLength(usv),
  }
}

// Writes an escaped usv to the given pointer
@unsafe
let writeEscapedUSV = (
  usv: WasmI32,
  strData: WasmArrayRef.WasmArrayRef,
  index: WasmI32,
  isString: Bool,
) => {
  use WasmI32.{ (+), (==) }
  let mut index = index
  if (computeEscapedUSVLength(usv, isString) == 2n) {
    index += writeUtf8CodePoint(strData, index, 0x5Cn) // \
  }
  index += writeUtf8CodePoint(strData, index, match (usv) {
    0x08n => 0x62n, // \b,
    0x0Cn => 0x66n, // \f
    0x0An => 0x6En, // \n
    0x0Dn => 0x72n, // \r
    0x09n => 0x74n, // \t
    0x0Bn => 0x76n, // \v
    0x5Cn => 0x5Cn, // \\
    0x27n when !isString => 0x27n, // \'
    0x22n when isString => 0x22n, // \"
    _ => usv,
  })
  index
}

// Determines the cycle number of a heap value
@unsafe
let rec getCycleNumber = (value: WasmRef, cycleMap: List<(WasmRef, Number)>) => {
  match (cycleMap) {
    [] => -1n,
    [(head, num), ..._] when head is value => untagSimpleNumber(num),
    [_, ...tail] => getCycleNumber(value, tail),
  }
}

/**
 * A container for the stringification logic.
 *
 * This can be exposed if we ever want to allow using the individual data type
 * stringification functions externally.
 */
module Stringify {
  // Settings
  @unsafe
  let defaultRadix = 10n // The default radix for numbers
  /**
   * State used during stringification to track cycles and context.
   */
  abstract record StringifyState {
    /** Indicates if we are currently stringifying the top-level value. */
    topLevel: Bool,
    /** A map of heap values to their cycle numbers. */
    cycleMap: Box<List<(WasmRef, Number)>>,
  }
  /**
   * Creates an initial empty stringification state.
   *
   * @returns An empty stringification state
   */
  provide let emptyState = () => { topLevel: true, cycleMap: box([]) }

  // Heap Values
  /**
   * Converts a String value to its string representation.
   *
   * @param val: The String value to convert
   *
   * @returns A document layout representing the stringified String value
   */
  @unsafe
  provide let string = (val: String, state) => {
    if (state.topLevel) {
      Doc.Builder.string(val)
    } else {
      use WasmI32.{ (+), (<) }
      let strRef = WasmRef.fromGrain(val)
      let strSize = DataStructures.getStringSize(strRef)
      let strData = DataStructures.getStringArrayRef(strRef)
      // Compute String Length with Escaping
      let mut escapedLength = 0n
      for (let mut i = 0n; i < strSize;) {
        let usv = Utf8.getCodePoint(strData, i)
        i += Utf8.usvEncodeLength(usv)
        escapedLength += computeEscapedUSVLength(usv, true)
      }
      // Write String with Escaping
      let escapedStrRef = allocateString(escapedLength)
      let escapedStrData = DataStructures.getStringArrayRef(escapedStrRef)
      let mut escapedIndex = 0n
      for (let mut i = 0n; i < strSize;) {
        let usv = Utf8.getCodePoint(strData, i)
        i += Utf8.usvEncodeLength(usv)
        escapedIndex = writeEscapedUSV(usv, escapedStrData, escapedIndex, true)
      }
      let content = Doc.Builder.string(WasmRef.toGrain(escapedStrRef): String)
      Doc.Builder.doubleQuotes(content)
    }
  }
  /**
   * Converts a Bytes value to its string representation.
   *
   * @param val: The Bytes value to convert
   *
   * @returns A document layout representing the stringified Bytes value
   */
  @unsafe
  provide let bytes = (val: Bytes) => {
    use Doc.Builder.{ (++) }
    use WasmI32.{ (+), (-), (*), (<), (>) }
    let ref = WasmRef.fromGrain(val)
    let data = DataStructures.getBytesArrayRef(ref)
    let size = DataStructures.getBytesSize(ref)
    let size = if (size > 32n) 32n else size // Limit to 32 bytes for display

    let hex = NumberUtils.get_HEX_DIGITS()
    let strLen = size * 3n - 1n // 2 hex digits + 1 space per byte - trailing space
    let strRef = allocateString(strLen)
    let strData = DataStructures.getStringArrayRef(strRef)
    WasmArrayRef.fillI8(strData, 0n, 0x20n, strLen) // Fill with spaces
    for (let mut i = 0n; i < size; i += 1n) {
      use WasmI32.{ (>>>) }
      let j = i * 3n
      let n = WasmArrayRef.getI8U(data, i) * 2n
      let hex = WasmI32.load16U(hex, n)
      WasmArrayRef.setI8(strData, j, hex)
      WasmArrayRef.setI8(strData, j + 1n, hex >>> 8n)
    }
    let content = Doc.Builder.string(WasmRef.toGrain(strRef): String)
    let content = if (size < 32n)
      content
    else
      content ++ Doc.Builder.constantString("...", 3)
    Doc.Builder.angleBrackets(
      Doc.Builder.constantString("bytes: ", 7) ++ content
    )
  }

  /**
   * Converts an Int8 byte value to its string representation.
   *
   * @param val: The Int8 value to convert
   *
   * @returns A document layout representing the stringified Int8 value
   */
  @unsafe
  provide let int8 = (val: Int8) =>
    Doc.Builder.string(NumberUtils.itoa32(untagInt8(val), defaultRadix))
  /**
   * Converts an Int16 value to its string representation.
   *
   * @param val: The Int16 value to convert
   *
   * @returns A document layout representing the stringified Int16 value
   */
  @unsafe
  provide let int16 = (val: Int16) =>
    Doc.Builder.string(NumberUtils.itoa32(untagInt16(val), defaultRadix))

  /**
   * Converts an Int32 value to its string representation.
   *
   * @param val: The Int32 value to convert
   *
   * @returns A document layout representing the stringified Int32 value
   */
  @unsafe
  provide let int32 = (val: Int32) => {
    let num = Conv.fromInt32(val)
    Doc.Builder.string(NumberUtils.itoa32(num, defaultRadix))
  }

  /**
   * Converts an Int64 value to its string representation.
   *
   * @param val: The Int64 value to convert
   *
   * @returns A document layout representing the stringified Int64 value
   */
  @unsafe
  provide let int64 = (val: Int64) => {
    let num = Conv.fromInt64(magic(val): Int64)
    Doc.Builder.string(NumberUtils.itoa64(num, defaultRadix))
  }

  /**
   * Converts a Uint8 byte value to its string representation.
   *
   * @param val: The Uint8 value to convert
   *
   * @returns A document layout representing the stringified Uint8 value
   */
  @unsafe
  provide let uint8 = (val: Uint8) =>
    Doc.Builder.string(NumberUtils.itoa32(untagUint8(val), defaultRadix))
  /**
   * Converts a Uint16 value to its string representation.
   *
   * @param val: The Uint16 value to convert
   *
   * @returns A document layout representing the stringified Uint16 value
   */
  @unsafe
  provide let uint16 = (val: Uint16) =>
    Doc.Builder.string(NumberUtils.itoa32(untagUint16(val), defaultRadix))

  /**
   * Converts a Uint32 value to its string representation.
   *
   * @param val: The Uint32 value to convert
   *
   * @returns A document layout representing the stringified Uint32 value
   */
  @unsafe
  provide let uint32 = (val: Uint32) => {
    let num = Conv.fromUint32(val)
    Doc.Builder.string(NumberUtils.utoa32(num, defaultRadix))
  }
  /**
   * Converts a Uint64 value to its string representation.
   *
   * @param val: The Uint64 value to convert
   *
   * @returns A document layout representing the stringified Uint64 value
   */
  @unsafe
  provide let uint64 = (val: Uint64) => {
    let num = Conv.fromUint64(val)
    Doc.Builder.string(NumberUtils.utoa64(num, defaultRadix))
  }

  /**
   * Converts a Float32 value to its string representation.
   *
   * @param val: The Float32 value to convert
   *
   * @returns A document layout representing the stringified Float32 value
   */
  @unsafe
  provide let float32 = (val: Float32) => {
    let num = Conv.fromFloat32(val)
    let num = WasmF64.promoteF32(num)
    Doc.Builder.string(NumberUtils.dtoa(num))
  }

  /**
   * Converts a Float64 value to its string representation.
   *
   * @param val: The Float64 value to convert
   *
   * @returns A document layout representing the stringified Float64 value
   */
  @unsafe
  provide let float64 = (val: Float64) => {
    let num = Conv.fromFloat64(val)
    Doc.Builder.string(NumberUtils.dtoa(num))
  }

  /**
   * Converts a Rational value to its string representation.
   *
   * @param val: The Rational value to convert
   *
   * @returns A document layout representing the stringified Rational value
   */
  @unsafe
  provide let rational = (val: Rational) => {
    use Doc.Builder.{ (++) }
    let ref = WasmRef.fromGrain(val)
    let numerator = DataStructures.getRationalNumerator(ref)
    let numerator = Bigint.bigIntToString(numerator, defaultRadix)
    let denominator = DataStructures.getRationalDenominator(ref)
    let denominator = Bigint.bigIntToString(denominator, defaultRadix)
    Doc.Builder.string(numerator)
      ++ Doc.Builder.constantString("/", 1)
      ++ Doc.Builder.string(denominator)
  }

  /**
   * Converts a BigInt value to its string representation.
   *
   * @param val: The BigInt value to convert
   *
   * @returns A document layout representing the stringified BigInt value
   */
  @unsafe
  provide let bigInt = (val: BigInt) => {
    let ref = WasmRef.fromGrain(val)
    let str = Bigint.bigIntToString(ref, defaultRadix)
    Doc.Builder.string(str)
  }

  /**
   * Converts a Char value to its string representation.
   *
   * @param val: The Char value to convert
   *
   * @returns A document layout representing the stringified Char value
   */
  @unsafe
  provide let char = (val: Char, state) => {
    let usv = untagChar(val)
    if (state.topLevel) {
      let strLength = usvEncodeLength(usv)
      let strRef = allocateString(strLength)
      let strData = DataStructures.getStringArrayRef(strRef)
      writeUtf8CodePoint(strData, 0n, usv)
      Doc.Builder.string(WasmRef.toGrain(strRef): String)
    } else {
      let strLength = computeEscapedUSVLength(usv, false)
      let strRef = allocateString(strLength)
      let strData = DataStructures.getStringArrayRef(strRef)
      writeEscapedUSV(usv, strData, 0n, false)
      Doc.Builder.singleQuotes(
        Doc.Builder.string(WasmRef.toGrain(strRef): String)
      )
    }
  }

  /**
   * Converts a Number value to its string representation.
   *
   * @param val: The Number value to convert
   *
   * @returns A document layout representing the stringified Number value
   */
  @unsafe
  provide let number = (val: Number) => {
    if (GrainValue.isSimpleNumberValue(val)) {
      Doc.Builder.string(
        NumberUtils.itoa32(untagSimpleNumber(val), defaultRadix)
      )
    } else {
      let ref = WasmRef.fromGrain(val)
      let tag = DataStructures.getNumberTag(ref)
      use WasmI32.{ (==) }
      match (tag) {
        _ when tag == Tags._GRAIN_INT64_BOXED_NUM_TAG => {
          int64(magic(val): Int64)
        },
        _ when tag == Tags._GRAIN_FLOAT64_BOXED_NUM_TAG => {
          float64(magic(val): Float64)
        },
        _ when tag == Tags._GRAIN_RATIONAL_BOXED_NUM_TAG => {
          rational(magic(val): Rational)
        },
        _ when tag == Tags._GRAIN_BIGINT_BOXED_NUM_TAG => {
          bigInt(magic(val): BigInt)
        },
        _ => Doc.Builder.constantString("<unknown number>", 16),
      }
    }
  }

  // Polymorphic conversions
  let shortValueToString = (ref: WasmRef, state) => {
    // Get The Short Tag
    match (ref) {
      _ when GrainValue.isChar(ref) => char(WasmRef.toGrain(ref): Char, state),
      _ when GrainValue.isInt8(ref) => int8(WasmRef.toGrain(ref): Int8),
      _ when GrainValue.isInt16(ref) => int16(WasmRef.toGrain(ref): Int16),
      _ when GrainValue.isUInt8(ref) => uint8(WasmRef.toGrain(ref): Uint8),
      _ when GrainValue.isUInt16(ref) => uint16(WasmRef.toGrain(ref): Uint16),
      _ => Doc.Builder.constantString("<unknown short value>", 21),
    }
  }

  // Constant Values
  @unsafe
  let constantValueToString = (ref: WasmRef) => {
    if (ref is WasmRef.fromGrain(true)) {
      Doc.Builder.constantString("true", 4)
    } else if (ref is WasmRef.fromGrain(false)) {
      Doc.Builder.constantString("false", 5)
    } else if (ref is WasmRef.fromGrain(void)) {
      Doc.Builder.constantString("void", 4)
    } else {
      Doc.Builder.constantString("<unknown constant value>", 24)
    }
  }
  @unsafe
  let rec heapValueToString = (ref: WasmRef, state) => {
    use Doc.Builder.{ (++) }
    use WasmI32.{ (==), (!=) }
    // Get The Heap Tag
    let tag = DataStructures.loadValueTag(ref)
    let content = match (tag) {
      _ when (
        tag == Tags._GRAIN_TUPLE_HEAP_TAG
        || tag == Tags._GRAIN_ARRAY_HEAP_TAG
        || tag == Tags._GRAIN_RECORD_HEAP_TAG
        || tag == Tags._GRAIN_ADT_HEAP_TAG
      )
        && DataStructures.loadCycleMarker(ref) != 0n => {
        let cycleMap = unbox(state.cycleMap)
        let cycleIndex = match (getCycleNumber(ref, cycleMap)) {
          -1n => {
            use WasmI32.{ (+) }
            let index = match (cycleMap) {
              [] => 1n,
              [(_, n), ..._] => untagSimpleNumber(n) + 1n,
            }
            state.cycleMap := [(ref, tagSimpleNumber(index)), ...cycleMap]
            index
          },
          n => n,
        }
        return Doc.Builder.constantString("<cycle to <", 11)
          ++ Doc.Builder.string(NumberUtils.itoa32(cycleIndex, defaultRadix))
          ++ Doc.Builder.constantString(">>", 2)
      },
      _ when tag == Tags._GRAIN_TUPLE_HEAP_TAG => tuple(ref, state),
      _ when tag == Tags._GRAIN_ARRAY_HEAP_TAG =>
        array(WasmRef.toGrain(ref): Array<WasmRef>, state),
      _ when tag == Tags._GRAIN_RECORD_HEAP_TAG => _record(ref, state),
      _ when tag == Tags._GRAIN_ADT_HEAP_TAG => adt(ref, state),
      _ when tag == Tags._GRAIN_LAMBDA_HEAP_TAG =>
        Doc.Builder.constantString("<lambda>", 8),
      _ when tag == Tags._GRAIN_STRING_HEAP_TAG =>
        string(WasmRef.toGrain(ref): String, state),
      _ when tag == Tags._GRAIN_BYTES_HEAP_TAG =>
        bytes(WasmRef.toGrain(ref): Bytes),
      _ when tag == Tags._GRAIN_BOXED_NUM_HEAP_TAG =>
        number(WasmRef.toGrain(ref): Number),
      _ when tag == Tags._GRAIN_INT32_HEAP_TAG =>
        int32(WasmRef.toGrain(ref): Int32),
      _ when tag == Tags._GRAIN_FLOAT32_HEAP_TAG =>
        float32(WasmRef.toGrain(ref): Float32),
      _ when tag == Tags._GRAIN_UINT32_HEAP_TAG =>
        uint32(WasmRef.toGrain(ref): Uint32),
      _ when tag == Tags._GRAIN_UINT64_HEAP_TAG =>
        uint64(WasmRef.toGrain(ref): Uint64),
      _ => Doc.Builder.constantString("<unknown heap value>", 20),
    }
    let cycleIndex = getCycleNumber(ref, unbox(state.cycleMap))
    return if (cycleIndex != -1n) {
      Doc.Builder.group(
        Doc.Builder.angleBrackets(
          Doc.Builder.string(NumberUtils.itoa32(cycleIndex, defaultRadix))
        )
          ++ Doc.Builder.blank(1)
          ++ content
      )
    } else {
      content
    }
  }
  and iterableItemHelp = (val: a, final: Bool, state) => {
    use Doc.Builder.{ (++) }
    let val = value(val, { ...state, topLevel: false })
    if (final) {
      Doc.Builder.group(val) ++ Doc.Builder.trailingComma
    } else {
      Doc.Builder.group(val ++ Doc.Builder.comma)
    }
  }
  and tupleHelp = (items: Array<WasmRef>, isVariant, state) => {
    use Doc.Builder.{ (++) }
    let content = Doc.Builder.parens(
      Doc.Builder.indent(
        Doc.Builder.concatArrayMap(
          lead=next => Doc.Builder._break,
          sep=(prev, next) => Doc.Builder.breakableSpace,
          trail=prev => Doc.Builder.empty,
          func=(final, item) =>
            iterableItemHelp(WasmRef.toGrain(item), final, state),
          items
        )
      )
        ++ Doc.Builder._break
    )
    match (items) {
      [> _] when !isVariant => Doc.Builder.constantString("box", 3) ++ content,
      _ => content,
    }
  }
  /**
   * Converts a tuple value to its string representation.
   *
   * @param ref: The tuple value to convert
   * @param state: The current stringification state
   *
   * @returns A document layout representing the stringified tuple value
   */
  and tuple = (ref: WasmRef, state) => {
    DataStructures.storeCycleMarker(ref, _VISITED_BIT)
    let data = GrainValue.getTupleData(ref)
    let content = tupleHelp(data, false, state)
    DataStructures.storeCycleMarker(ref, 0n)
    content
  }
  /**
   * Converts an array value to its string representation.
   *
   * @param val: The array value to convert
   * @param state: The current stringification state
   *
   * @returns A document layout representing the stringified array value
   */
  and array = (val: Array<a>, state) => {
    use Doc.Builder.{ (++) }
    let ref = WasmRef.fromGrain(val)
    DataStructures.storeCycleMarker(ref, _VISITED_BIT)
    let content = Doc.Builder.arrayBrackets(
      Doc.Builder.indent(
        Doc.Builder.concatArrayMap(
          lead=next => Doc.Builder._break,
          sep=(prev, next) => Doc.Builder.breakableSpace,
          trail=prev => Doc.Builder.empty,
          func=(final, item) =>
            iterableItemHelp(WasmRef.toGrain(item), final, state),
          magic(val): Array<WasmRef>
        )
      )
        ++ Doc.Builder._break
    )
    DataStructures.storeCycleMarker(ref, 0n)
    content
  }
  /**
   * Converts a list value to its string representation.
   *
   * @param val: The list value to convert
   * @param state: The current stringification state
   *
   * @returns A document layout representing the stringified list value
   */
  and list = (val: List<a>, state) => {
    use Doc.Builder.{ (++) }
    Doc.Builder.listBrackets(
      Doc.Builder.indent(
        Doc.Builder.concatMap(
          lead=next => Doc.Builder._break,
          sep=(prev, next) => Doc.Builder.breakableSpace,
          trail=prev => Doc.Builder.empty,
          func=(final, item) =>
            iterableItemHelp(WasmRef.toGrain(item), final, state),
          val
        )
      )
        ++ Doc.Builder._break
    )
  }
  /**
   * Converts an ADT value to its string representation.
   *
   * @param ref: The ADT value to convert
   * @param state: The current stringification state
   *
   * @returns A document layout representing the stringified ADT value
   */
  and adt = (ref: WasmRef, state) => {
    use Doc.Builder.{ (++) }
    DataStructures.storeCycleMarker(ref, _VISITED_BIT)
    let content = if (GrainValue.isListVariant(ref)) {
      list(WasmRef.toGrain(ref), { ...state, topLevel: false })
    } else {
      let (name, variantData) = GrainValue.getVariantData(ref)
      Doc.Builder.string(name) ++ match (variantData) {
        GrainValue.TupleVariant(vals) =>
          tupleHelp(vals, true, { ...state, topLevel: false }),
        GrainValue.RecordVariant(vals) =>
          _recordHelp(vals, { ...state, topLevel: false }),
        EmptyVariant => Doc.Builder.empty,
      }
    }
    DataStructures.storeCycleMarker(ref, 0n)
    content
  }
  and _recordHelp = (entries: Array<(String, WasmRef)>, state) => {
    use Doc.Builder.{ (++) }
    Doc.Builder.braces(
      Doc.Builder.indent(
        Doc.Builder.concatArrayMap(
          lead=next => Doc.Builder.space ++ Doc.Builder._break,
          sep=(prev, next) => Doc.Builder.breakableSpace,
          trail=last => Doc.Builder.space,
          func=(final, (name, ref)) => {
            let val = value(WasmRef.toGrain(ref), { ...state, topLevel: false })
            let entry = Doc.Builder.group(
              Doc.Builder.string(name)
                ++ Doc.Builder.constantString(":", 1)
                ++ Doc.Builder.space
                ++ val
            )
            if (final) {
              entry ++ match (entries) {
                [> _] => Doc.Builder.comma,
                _ => Doc.Builder.trailingComma,
              }
            } else {
              Doc.Builder.group(entry ++ Doc.Builder.comma)
            }
          },
          entries
        )
      )
        ++ Doc.Builder._break
    )
  }
  /**
   * Converts a record value to its string representation.
   *
   * @param ref: The record value to convert
   * @param state: The current stringification state
   *
   * @returns A document layout representing the stringified record value
   */
  and _record = (ref: WasmRef, state) => {
    DataStructures.storeCycleMarker(ref, _VISITED_BIT)
    let content = _recordHelp(GrainValue.getRecordData(ref), state)
    DataStructures.storeCycleMarker(ref, 0n)
    content
  }
  /**
   * Converts a Grain value to its string representation.
   *
   * @param value: The grain value to convert
   * @param state: The current stringification state
   *
   * @returns A document layout representing the stringified value
   */
  and value = (value: a, state) => {
    let ref = WasmRef.fromGrain(value)
    if (GrainValue.isSimpleNumberValue(value)) {
      number(magic(value): Number)
    } else if (GrainValue.isHeapValue(value)) {
      heapValueToString(ref, state)
    } else if (GrainValue.isShortValue(value)) {
      shortValueToString(ref, state)
    } else if (GrainValue.isConstantValue(value)) {
      constantValueToString(ref)
    } else {
      Doc.Builder.constantString("<unknown value>", 15)
    }
  }

  provide { value, array, list, tuple, _record, adt }
}

/**
 * Converts any Grain value to its string representation.
 *
 * @param val: The Grain value to convert
 *
 * @returns The string representation of the Grain value
 */
provide let toString = (val: a) => {
  // Note: This is a bit of hack to get around grain's lack of forall types
  let val = magic(val): b
  let ast = Stringify.value(val, Stringify.emptyState())
  Doc.Engine.toString(LF, 80, ast)
}
