/*
 * Copyright (c) 2025 Jake Follest
 * Licensed under the MIT License.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies, subject to the MIT License.
 */

/**
 * Unsafe utilities for extracting runtime tag information from grain values.
 *
 *
 * Note:
 *   This module is unsafe and should be used with caution.
 *   The grain team offers no guarantees on breaking changes or
 *   end user support.
 */
@noPervasives
module GrainValue

from "runtime/unsafe/wasmref" include WasmRef
use WasmRef.{ module WasmArrayRef }
from "runtime/unsafe/wasmi32" include WasmI32
use WasmI32.{ (+), (-), remS as (%), (&), (<<), (==), (!=), (>=), (<), (>) }
from "runtime/unsafe/memory" include Memory
from "runtime/unsafe/tags" include Tags
from "runtime/dataStructures" include DataStructures
use DataStructures.{
  allocateString,
  getStringArrayRef,
  allocateArray,
  getCompoundValueArrayRef,
  untagSimpleNumber,
  tagSimpleNumber,
}

exception Impossible(String)

primitive (&&) = "@and"
primitive builtinId = "@builtin.id"
primitive throw = "@throw"

@unsafe
let _LIST_ID = untagSimpleNumber(builtinId("List"))
@unsafe
let _OPTION_ID = untagSimpleNumber(builtinId("Option"))
@unsafe
let _RESULT_ID = untagSimpleNumber(builtinId("Result"))
@unsafe
let _RANGE_ID = untagSimpleNumber(builtinId("Range"))

// Stack tagging
/**
 * Checks if the given grain value is a simple number.
 *
 * @param val: The grain value to check
 *
 * @returns `true` if the grain value is a simple number, `false` otherwise
 */
@unsafe
provide let isSimpleNumberValue = val => {
  let ref = WasmRef.fromGrain(val)
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_NUMBER_TAG_MASK)
      == Tags._GRAIN_NUMBER_TAG_TYPE
}

/**
 * Checks if the given grain value is a heap value.
 *
 * @param val: The grain value to check
 *
 * @returns `true` if the grain value is a heap value, `false` otherwise
 */
@unsafe
provide let isHeapValue = val => {
  let ref = WasmRef.fromGrain(val)
  WasmRef.isGrainHeapValue(ref)
}

/**
 * Checks if the given grain value is a constant value.
 *
 * @param val: The grain value to check
 *
 * @returns `true` if the grain value is a constant value, `false` otherwise
 */
@unsafe
provide let isConstantValue = val => {
  let ref = WasmRef.fromGrain(val)
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_TAG_MASK)
      == Tags._GRAIN_CONST_TAG_TYPE
}

/**
 * Checks if the given grain value is a short value.
 *
 * @param val: The grain value to check
 *
 * @returns `true` if the grain value is a short value, `false` otherwise
 */
@unsafe
provide let isShortValue = val => {
  let ref = WasmRef.fromGrain(val)
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_TAG_MASK)
      == Tags._GRAIN_SHORTVAL_TAG_TYPE
}

// Short tagging
/**
 * Checks if the given grain value is a char short value.
 *
 * @param ref: The grain value to check
 *
 * @returns `true` if the grain value is a char short value, `false` otherwise
 */
@unsafe
provide let isChar = ref => {
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_SHORTVAL_TAG_MASK)
      == Tags._GRAIN_CHAR_SHORTVAL_TAG
}

/**
 * Checks if the given grain value is a int8 short value.
 *
 * @param ref: The grain value to check
 *
 * @returns `true` if the grain value is a int8 short value, `false` otherwise
 */
@unsafe
provide let isInt8 = ref => {
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_SHORTVAL_TAG_MASK)
      == Tags._GRAIN_INT8_TAG_MASK
}

/**
 * Checks if the given grain value is a int16 short value.
 *
 * @param ref: The grain value to check
 *
 * @returns `true` if the grain value is a int16 short value, `false` otherwise
 */
@unsafe
provide let isInt16 = ref => {
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_SHORTVAL_TAG_MASK)
      == Tags._GRAIN_INT16_TAG_MASK
}

/**
 * Checks if the given grain value is a uint8 short value.
 *
 * @param ref: The grain value to check
 *
 * @returns `true` if the grain value is a uint8 short value, `false` otherwise
 */
@unsafe
provide let isUInt8 = ref => {
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_SHORTVAL_TAG_MASK)
      == Tags._GRAIN_UINT8_TAG_MASK
}

/**
 * Checks if the given grain value is a uint16 short value.
 *
 * @param ref: The grain value to check
 *
 * @returns `true` if the grain value is a uint16 short value, `false` otherwise
 */
@unsafe
provide let isUInt16 = ref => {
  WasmRef.isRefI31(ref)
    && (WasmRef.i31GetU(ref) & Tags._GRAIN_GENERIC_SHORTVAL_TAG_MASK)
      == Tags._GRAIN_UINT16_TAG_MASK
}

/**
 * Provides the tuples tagged contents.
 *
 * @param ref: A reference to the tuple value to extract data from
 *
 * @returns An array of values representing the tuple's elements
 */
@unsafe
provide let getTupleData = (ref: WasmRef) => {
  let data = getCompoundValueArrayRef(ref)
  let arity = WasmArrayRef.length(data)
  let arrRef = allocateArray(arity, WasmRef.fromGrain(void))
  let arrData = getCompoundValueArrayRef(arrRef)
  for (let mut i = 0n; i < arity; i += 1n) {
    WasmArrayRef.setAny(arrData, i, WasmArrayRef.getAny(data, i))
  }
  WasmRef.toGrain(arrRef): Array<WasmRef>
}

/**
 * Provides utilities for accessing type metadata.
 */
module TypeMetaData {
  @unsafe
  primitive typeMetadata = "@heap.type_metadata"

  /**
   * Finds the type metadata block for a given type hash.
   *
   * @param typeHash: The type hash to find metadata for
   *
   * @returns Pointer to the type metadata block, or -1n if not found
   */
  @unsafe
  provide let findTypeMetadata = typeHash => {
    // Get the pointer to the type metadata table
    let mut typeMetadata = typeMetadata()
    if (typeMetadata == 0n) return -1n // No metadata registered
    let numBuckets = WasmI32.load(typeMetadata, 0n)
    if (WasmI32.eqz(numBuckets)) return -1n // No buckets in metadata table
    // Locate the block
    let bucketHash = (typeHash % numBuckets) << 3n // 8 bytes per entry
    let bucketPtr = typeMetadata + 8n + bucketHash // First 8 bytes of metadata are for table size
    // Locate the bucket
    let bucketOffset = WasmI32.load(bucketPtr, 0n)
    let bucketSize = WasmI32.load(bucketPtr, 4n)
    // Scan the bucket entries for matching type hash
    let startPtr = typeMetadata + bucketOffset
    let endPtr = startPtr + (bucketSize << 3n) // 8 bytes per entry
    for (let mut blockPtr = startPtr; blockPtr < endPtr; blockPtr += 8n) {
      let blockHash = WasmI32.load(blockPtr, 0n)
      if (blockHash == typeHash) {
        return typeMetadata + WasmI32.load(blockPtr, 4n) // Metadata pointer
      }
    }
    return -1n
  }

  /**
   * Provides the metadata for a record type.
   *
   * @param metaDataPtr: Pointer to the record metadata block
   * @param typeTag: The record type tag
   * @param arity: Number of fields in the record
   *
   * @returns The names of the fields in the record, or an empty array if none found
   */
  @unsafe
  provide let getRecordMetaData = (metaDataPtr, typeTag, arity) => {
    if (metaDataPtr == -1n) {
      // Possible built-in record type
      if (typeTag == _RANGE_ID) {
        [> "rangeStart", "rangeEnd"]
      } else {
        [>]
      }
    } else {
      // +0  32-bit size of complete type info block
      // <start repeated pattern>
      // +0  32-bit size of record field name block
      // +4  32-bit length of record field name
      // +8  n-bit string
      // <end repeated pattern>
      let metaDataSize = WasmI32.load(metaDataPtr, 0n)
      let metaDataEndPtr = metaDataPtr + metaDataSize
      let mut metaDataPtr = metaDataPtr + 4n // Skip block size field
      // Read Blocks
      let fieldArrayRef = allocateArray(arity, WasmRef.fromGrain(void))
      let fieldArrayData = getCompoundValueArrayRef(fieldArrayRef)
      for (let mut i = 0n; i < arity; i += 1n) {
        if (metaDataPtr > metaDataEndPtr)
          throw Impossible("Invalid record metadata")
        // Read the field
        let fieldBlockSize = WasmI32.load(metaDataPtr, 0n)
        let fieldLength = WasmI32.load(metaDataPtr, 4n)
        let fieldNameRef = allocateString(fieldLength)
        let fieldNameData = getStringArrayRef(fieldNameRef)
        Memory.copyLinearMemoryToRefArray(
          fieldNameData,
          metaDataPtr + 8n, // +4 to skip field size
          fieldLength // +4 for 32-bit field length
        )
        // Write to array
        WasmArrayRef.setAny(fieldArrayData, i, fieldNameRef)
        // Advance to next field
        metaDataPtr += fieldBlockSize
      }
      WasmRef.toGrain(fieldArrayRef): Array<String>
    }
  }

  /**
   * Provides the metadata for a variant type.
   *
   * @param metaDataPtr: Pointer to the variant metadata block
   * @param typeTag: The variant type tag
   * @param variantTag: The variant tag
   * @param arity: Number of fields in the variant
   *
   * @returns The name and fields of the variant
   */
  @unsafe
  provide let getVariantMetaData = (metaDataPtr, typeTag, variantTag, arity) => {
    if (metaDataPtr == -1n) {
      return (
        if (typeTag == _OPTION_ID) {
          if (variantTag == 0n) {
            "Some"
          } else {
            "None"
          }
        } else if (typeTag == _RESULT_ID) {
          if (variantTag == 0n) {
            "Ok"
          } else {
            "Err"
          }
        } else {
          "<unknown variant>"
        },
        [>],
      )
    } else {
      // +0  32-bit size of complete type info block
      // <start repeated pattern>
      // +0  32-bit size of constructor name block
      // +4  32-bit offset to field data (for inline record constructors) or 0 (for tuple-like constructors)
      // +4  32-bit constructor id
      // +8  32-bit length of constructor name
      // +12 n-bit string
      //   <start repeated pattern> (only for inline record constructors)
      //   +0  32-bit size of record field name block
      //   +4  32-bit length of record field name
      //   +8  n-bit string
      //   <end repeated pattern>
      // <end repeated pattern>
      let metaDataSize = WasmI32.load(metaDataPtr, 0n)
      let metaDataEndPtr = metaDataPtr + metaDataSize
      let mut currentPtr = metaDataPtr + 4n // Skip block size field
      // Locate the variant metadata
      while (currentPtr < metaDataEndPtr) {
        // Check variant tag
        let constructorBlockSize = WasmI32.load(currentPtr, 0n)
        let constructorId = WasmI32.load(currentPtr, 8n)
        if (constructorId != variantTag) {
          currentPtr += constructorBlockSize
          continue
        }
        // Read Variant Name
        let nameLength = WasmI32.load(currentPtr, 12n)
        let nameRef = allocateString(nameLength)
        let nameData = getStringArrayRef(nameRef)
        Memory.copyLinearMemoryToRefArray(
          nameData,
          currentPtr + 16n, // +16 to skip size(4) + offset(4) + id(4)
          nameLength // +4 for 32-bit field length
        )
        // Read Variant Fields
        let fieldOffset = WasmI32.load(currentPtr, 4n)
        if (fieldOffset == 0n) return (WasmRef.toGrain(nameRef): String, [>]) // Tuple variant
        let fieldArrayRef = allocateArray(arity, WasmRef.fromGrain(void))
        let fieldArrayData = getCompoundValueArrayRef(fieldArrayRef)
        let mut fieldMetaDataPtr = currentPtr + fieldOffset
        for (let mut i = 0n; i < arity; i += 1n) {
          // Read the field
          let fieldBlockSize = WasmI32.load(fieldMetaDataPtr, 0n)
          let fieldLength = WasmI32.load(fieldMetaDataPtr, 4n)
          let fieldNameRef = allocateString(fieldLength)
          let fieldNameData = getStringArrayRef(fieldNameRef)
          Memory.copyLinearMemoryToRefArray(
            fieldNameData,
            fieldMetaDataPtr + 8n, // +4 to skip field size
            fieldLength // +4 for 32-bit field length
          )
          // Write to array
          WasmArrayRef.setAny(fieldArrayData, i, fieldNameRef)
          // Advance to next field
          fieldMetaDataPtr += fieldBlockSize
        }
        return (
          WasmRef.toGrain(nameRef): String,
          WasmRef.toGrain(fieldArrayRef): Array<String>,
        )
      }
      throw Impossible("Invalid variant metadata")
    }
  }
}

/**
 * Provides the record's tagged field data.
 *
 * @param record_: The tagged record value to extract data from
 *
 * @returns An associated array of field names and their corresponding tagged values
 */
@unsafe
provide let getRecordData = (record_: WasmRef) => {
  let ref = WasmRef.fromGrain(record_)
  let data = getCompoundValueArrayRef(ref)
  let typeHash = untagSimpleNumber(DataStructures.loadRecordTypeHash(ref))
  let typeTag = untagSimpleNumber(DataStructures.loadRecordTypeId(ref))
  let arity = WasmArrayRef.length(data)
  // Lookup Metadata
  let metaDataPtr = TypeMetaData.findTypeMetadata(typeHash)
  // Get field names
  let fieldNamesRef = WasmRef.fromGrain(
    TypeMetaData.getRecordMetaData(metaDataPtr, typeTag, arity)
  )
  let fieldNamesData = getCompoundValueArrayRef(fieldNamesRef)
  let noMetaData = WasmArrayRef.length(fieldNamesData) == 0n
  // Get field data
  let fieldRef = allocateArray(arity, WasmRef.fromGrain(void))
  let fieldData = getCompoundValueArrayRef(fieldRef)
  for (let mut i = arity - 1n; i >= 0n; i -= 1n) {
    // Determine field name
    let name = if (noMetaData) {
      "<unknown field>"
    } else {
      WasmRef.toGrain(WasmArrayRef.getAny(fieldNamesData, i)): String
    }
    // Determine field value
    let value = WasmArrayRef.getAny(data, i)
    // Pack data
    WasmArrayRef.setAny(fieldData, i, WasmRef.fromGrain((name, value)))
  }
  WasmRef.toGrain(fieldRef): Array<(String, WasmRef)>
}

/**
 * Represents the variant's field data types.
 *
 * Note: The `a` is `forall a`, meaning we never want to unify it.
 */
provide enum VariantType<a> {
  /** A variant with no attached data. */
  EmptyVariant,
  /** A variant with tuple data attached. */
  TupleVariant(Array<WasmRef>),
  /** A variant with record data attached. */
  RecordVariant(Array<(String, WasmRef)>),
}

/**
 * Provides the variant's tagged field data.
 *
 * @param ref: A reference to the variant value to extract data from
 *
 * @returns The name and field data of the variant
 */
@unsafe
provide let getVariantData = (ref: WasmRef) => {
  let data = getCompoundValueArrayRef(ref)
  let typeHash = untagSimpleNumber(DataStructures.loadVariantTypeHash(ref))
  let typeTag = untagSimpleNumber(DataStructures.loadVariantTypeId(ref))
  let variantTag = untagSimpleNumber(DataStructures.loadAdtVariant(ref))
  let arity = WasmArrayRef.length(data)
  // Lookup Metadata
  let metaDataPtr = TypeMetaData.findTypeMetadata(typeHash)
  // Get Names
  let (name, fields) = TypeMetaData.getVariantMetaData(
    metaDataPtr,
    typeTag,
    variantTag,
    arity
  )
  if (arity == 0n) return (name, EmptyVariant)
  let fieldNames = getCompoundValueArrayRef(WasmRef.fromGrain(fields))
  let isTuple = WasmArrayRef.length(fieldNames) == 0n
  // Get Data
  let valuesRef = allocateArray(arity, WasmRef.fromGrain(void))
  let valuesData = getCompoundValueArrayRef(valuesRef)
  for (let mut i = arity - 1n; i >= 0n; i -= 1n) {
    // Determine field value
    let value = WasmArrayRef.getAny(data, i)
    // Write to data array
    WasmArrayRef.setAny(valuesData, i, if (isTuple) {
      value
    } else {
      let field = WasmArrayRef.getAny(fieldNames, i)
      WasmRef.fromGrain((field, value))
    })
  }
  // Pack Data
  return (name, if (isTuple) {
    TupleVariant(WasmRef.toGrain(valuesRef): Array<WasmRef>)
  } else {
    RecordVariant(WasmRef.toGrain(valuesRef): Array<(String, WasmRef)>)
  })
}

/**
 * Checks if the given ADT value is a List variant.
 *
 * @param ref: The ADT value to check.
 *
 * @returns `true` if the ADT value is a List variant, `false` otherwise.
 */
@unsafe
provide let isListVariant = (ref: WasmRef) => {
  let typeId = untagSimpleNumber(DataStructures.loadVariantTypeId(ref))
  typeId == _LIST_ID
}
